jobs:
  include:
    - stage: build image
      services:
        - docker
      before_script:
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
      script:
        - docker build -t bombergame/service-monitor .
      after_success:
        - if [ ${TRAVIS_BRANCH} = "master" ]; then
          docker push bombergame/service-monitor;
          fi
