scrape_configs:
  - job_name: auth-service
      scrape_interval: 15s
      static_configs:
        - targets:
            - auth-service:80
  - job_name: profiles-service
      scrape_interval: 15s
      static_configs:
        - targets:
            - profiles-service:80
