global:
  scrape_interval: 1m
  external_labels:
    monitor: 'bombergame-monitor'

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:80']
    metrics_path: '/metrics'
  - job_name: 'profiles-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['profiles-service:80']
  - job_name: 'multiplayer-service'
    scrape_interval: 60s
    static_configs:
      - targets: ['multiplayer-service:80']
