global:
  scrape_interval: 30s
  external_labels:
    monitor: 'bombergame-monitor'

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:80']
  - job_name: 'profiles-service'
    scrape_interval: 60s
    static_configs:
      - targets: ['profiles-service:80']
